ARCv3: update list of symbols exported from libgcc
Extend list of exported from libgcc symbols for ARCv3.
This patch fixes build of XFS, BTRFS and some other modules for ARCv3
targets:

ERROR: modpost: "__ucmpdi2" [fs/btrfs/btrfs.ko] undefined!
ERROR: modpost: "__lshrdi3" [fs/btrfs/btrfs.ko] undefined!
ERROR: modpost: "__ashldi3" [fs/btrfs/btrfs.ko] undefined!
ERROR: modpost: "__ucmpdi2" [fs/xfs/xfs.ko] undefined!
ERROR: modpost: "__lshrdi3" [fs/xfs/xfs.ko] undefined!

This is an extension for commit 88b0c1c (ARCv3: HS5x libgcc lacks
math emulation)

Signed-off-by: Pavel Kozlov <pavel.kozlov@synopsys.com>